// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Virtuoso.Miranda.Plugins.Infrastructure;
namespace Virtuoso.Miranda.Plugins.UnitTests
{
    /// <summary>
    ///This is a test class for Virtuoso.Miranda.Plugins.Infrastructure.NetworkProtocol and is intended
    ///to contain all Virtuoso.Miranda.Plugins.Infrastructure.NetworkProtocol Unit Tests
    ///</summary>
    [TestClass()]
    public class NetworkProtocolTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for NetworkProtocol (PROTOCOLDESCRIPTOR)
        ///</summary>
        [TestMethod(), ExpectedException(typeof(ArgumentException))]
        public void ConstructorTest()
        {
            Virtuoso_Miranda_Plugins_Native_PROTOCOLDESCRIPTORAccessor d = new Virtuoso_Miranda_Plugins_Native_PROTOCOLDESCRIPTORAccessor(null);
            Virtuoso_Miranda_Plugins_Infrastructure_NetworkProtocolAccessor.CreatePrivate(ref d);
        }
    }
}
