//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virtuoso.Miranda.Plugins.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfigurationDialog_HideExpertOptions_Checked {
            get {
                return ((bool)(this["ConfigurationDialog_HideExpertOptions_Checked"]));
            }
            set {
                this["ConfigurationDialog_HideExpertOptions_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tile")]
        public global::System.Windows.Forms.View ConfigurationPanel_CategoryItems_View {
            get {
                return ((global::System.Windows.Forms.View)(this["ConfigurationPanel_CategoryItems_View"]));
            }
            set {
                this["ConfigurationPanel_CategoryItems_View"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("792, 562")]
        public global::System.Drawing.Size ConfigurationDialog_ClientSize {
            get {
                return ((global::System.Drawing.Size)(this["ConfigurationDialog_ClientSize"]));
            }
            set {
                this["ConfigurationDialog_ClientSize"] = value;
            }
        }
    }
}
