//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virtuoso.Miranda.Plugins.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Virtuoso.Miranda.Plugins.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphen plugins are enabled and ready to use..
        /// </summary>
        internal static string Balloon_Text_FusionFinished {
            get {
                return ResourceManager.GetString("Balloon_Text_FusionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Config_General {
            get {
                return ResourceManager.GetString("Config_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Config_General_About {
            get {
                return ResourceManager.GetString("Config_General_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hyphen copyright information..
        /// </summary>
        internal static string Config_General_About_Description {
            get {
                return ResourceManager.GetString("Config_General_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Hyphen information..
        /// </summary>
        internal static string Config_General_Description {
            get {
                return ResourceManager.GetString("Config_General_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Config_Management {
            get {
                return ResourceManager.GetString("Config_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Hyphen plugins..
        /// </summary>
        internal static string Config_Management_Description {
            get {
                return ResourceManager.GetString("Config_Management_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string Config_Management_Plugins {
            get {
                return ResourceManager.GetString("Config_Management_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable Hyphen plugins on individual basis..
        /// </summary>
        internal static string Config_Management_Plugins_Description {
            get {
                return ResourceManager.GetString("Config_Management_Plugins_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not supported for an unknown protocol..
        /// </summary>
        internal static string ExceptionMsg_CallInvalidForUnknownNetworkProtocol {
            get {
                return ResourceManager.GetString("ExceptionMsg_CallInvalidForUnknownNetworkProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot detect the default string encoding used in Miranda..
        /// </summary>
        internal static string ExceptionMsg_CannotDetectMirandaDefaultStringEncoding {
            get {
                return ResourceManager.GetString("ExceptionMsg_CannotDetectMirandaDefaultStringEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred in the PluginManager while working with unmanaged memory. Contact Hyphen vendor, please..
        /// </summary>
        internal static string ExceptionMsg_CannotFinishMarshaling {
            get {
                return ResourceManager.GetString("ExceptionMsg_CannotFinishMarshaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while opening plugin home page..
        /// </summary>
        internal static string ExceptionMsg_CannotOpenHomePage {
            get {
                return ResourceManager.GetString("ExceptionMsg_CannotOpenHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register/unregister builtin protocol. Only custom protocol can be registered/unregistered..
        /// </summary>
        internal static string ExceptionMsg_CannotRegisterBuiltinProtocol {
            get {
                return ResourceManager.GetString("ExceptionMsg_CannotRegisterBuiltinProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize Hyphen configuration. .
        /// </summary>
        internal static string ExceptionMsg_ConfigurationFailed {
            get {
                return ResourceManager.GetString("ExceptionMsg_ConfigurationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicit loader options detected. RequiredVersion or MinimalMirandaVersion were set by a base class previously..
        /// </summary>
        internal static string ExceptionMsg_DuplicitLoaderOptions {
            get {
                return ResourceManager.GetString("ExceptionMsg_DuplicitLoaderOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete the service call. .
        /// </summary>
        internal static string ExceptionMsg_ErrorWhileCallingMirandaService {
            get {
                return ResourceManager.GetString("ExceptionMsg_ErrorWhileCallingMirandaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading plugins..
        /// </summary>
        internal static string ExceptionMsg_ErrorWhileLoadingPlugins {
            get {
                return ResourceManager.GetString("ExceptionMsg_ErrorWhileLoadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature is not available from current domain..
        /// </summary>
        internal static string ExceptionMsg_FeatureNotAvailableInDomain {
            get {
                return ResourceManager.GetString("ExceptionMsg_FeatureNotAvailableInDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load plugin &apos;{0}&apos; - {1}.
        /// </summary>
        internal static string ExceptionMsg_Formatable1_AssemblyLoadError {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_AssemblyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load string resolver of type &apos;{0}&apos;. Check if there is a public default .ctor..
        /// </summary>
        internal static string ExceptionMsg_Formatable1_CannotLoadStringResolver {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_CannotLoadStringResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed hooking event &apos;{0}&apos;. Check event name..
        /// </summary>
        internal static string ExceptionMsg_Formatable1_EventHookingFailed {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_EventHookingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load plugin &apos;{0}&apos; - this plugin cannot be loaded automatically..
        /// </summary>
        internal static string ExceptionMsg_Formatable1_ExplicitPluginLoadForbidden {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_ExplicitPluginLoadForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process method &apos;{0}&apos; - method signature does not match required delegate signature..
        /// </summary>
        internal static string ExceptionMsg_Formatable1_InvalidMethodSignature {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_InvalidMethodSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot instantiate plugin type &apos;{0}&apos; - no valid constructor found..
        /// </summary>
        internal static string ExceptionMsg_Formatable1_NoValidPluginCtorFound {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_NoValidPluginCtorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create service function &apos;{0}&apos; - the service already exists..
        /// </summary>
        internal static string ExceptionMsg_Formatable1_ServiceFunctionAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_ServiceFunctionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating service function &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionMsg_Formatable1_ServiceFunctionCreationFailed {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_ServiceFunctionCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master type for the {0} standalone plugin proxy not found..
        /// </summary>
        internal static string ExceptionMsg_Formatable1_UnableToLoadMasterType {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_UnableToLoadMasterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize plugin descriptor - {0}.
        /// </summary>
        internal static string ExceptionMsg_Formatable1_UnableToSetUpPluginDescriptor {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_UnableToSetUpPluginDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while instantiating plugin type &apos;{0}&apos; - Hyphen is not allowed to load the plugin..
        /// </summary>
        internal static string ExceptionMsg_Formatable1_UnauthorizedToInstantiatePlugin {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_UnauthorizedToInstantiatePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load plugin &apos;{0}&apos; - the image is not a valid CLI assembly..
        /// </summary>
        internal static string ExceptionMsg_Formatable1_UnmanagedImageFound {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_UnmanagedImageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while instantiating plugin type &apos;{0}&apos; - constructor threw an exception ({1})..
        /// </summary>
        internal static string ExceptionMsg_Formatable2_ErrorWhileInstantiatingPlugin {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable2_ErrorWhileInstantiatingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete requested operation - Miranda service &apos;{0}&apos; returned {1}..
        /// </summary>
        internal static string ExceptionMsg_Formatable2_MirandaServiceReturnedFailure {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable2_MirandaServiceReturnedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} requires {1} but this version is not available, the plugin cannot be loaded. Please download the latest version..
        /// </summary>
        internal static string ExceptionMsg_Formatable2_RuntimeVersionNotAvailable {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable2_RuntimeVersionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot associate menu item &apos;{0}&apos; with method &apos;{1}&apos; - the item is already associated with service &apos;{2}&apos;..
        /// </summary>
        internal static string ExceptionMsg_Formatable3_MenuItemServiceAlreadySet {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable3_MenuItemServiceAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook not found..
        /// </summary>
        internal static string ExceptionMsg_HookNotFound {
            get {
                return ResourceManager.GetString("ExceptionMsg_HookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Hyphen plugins are not supported side-by-side..
        /// </summary>
        internal static string ExceptionMsg_HyphenSxSNotSupported {
            get {
                return ResourceManager.GetString("ExceptionMsg_HyphenSxSNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred in Hyphen. Please contact Hyphen&apos;s author..
        /// </summary>
        internal static string ExceptionMsg_InternalErrorOccurred {
            get {
                return ResourceManager.GetString("ExceptionMsg_InternalErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the InteropBuffer without locking it before..
        /// </summary>
        internal static string ExceptionMsg_InteropBufferNotLocked {
            get {
                return ResourceManager.GetString("ExceptionMsg_InteropBufferNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform the requested operation on a locked buffer..
        /// </summary>
        internal static string ExceptionMsg_InteropBufferNotUnlocked {
            get {
                return ResourceManager.GetString("ExceptionMsg_InteropBufferNotUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unlock the buffer from a thread that does not locked it..
        /// </summary>
        internal static string ExceptionMsg_InvalidCrossThreadInteropBufferUnlock {
            get {
                return ResourceManager.GetString("ExceptionMsg_InvalidCrossThreadInteropBufferUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fusion context..
        /// </summary>
        internal static string ExceptionMsg_InvalidFusionContext {
            get {
                return ResourceManager.GetString("ExceptionMsg_InvalidFusionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handle is invalid..
        /// </summary>
        internal static string ExceptionMsg_InvalidHandle {
            get {
                return ResourceManager.GetString("ExceptionMsg_InvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot translate this value - invalid value address or value format..
        /// </summary>
        internal static string ExceptionMsg_InvalidValueToTranslate {
            get {
                return ResourceManager.GetString("ExceptionMsg_InvalidValueToTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load plugins - I/O error occurred. Check if you have permissions to access the &apos;Miranda\plugins\managed&apos; directory..
        /// </summary>
        internal static string ExceptionMsg_IOErrorOccurred {
            get {
                return ResourceManager.GetString("ExceptionMsg_IOErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miranda context has not been initialized yet. The context will be initialialized in the Load export, until then, context calls are not supported..
        /// </summary>
        internal static string ExceptionMsg_MirandaContextNotAvailable {
            get {
                return ResourceManager.GetString("ExceptionMsg_MirandaContextNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miranda must be restarted..
        /// </summary>
        internal static string ExceptionMsg_MirandaRestartRequired {
            get {
                return ResourceManager.GetString("ExceptionMsg_MirandaRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read the setting on behalf of the owning module - the owning module cannot be determined..
        /// </summary>
        internal static string ExceptionMsg_OwnerUnknown {
            get {
                return ResourceManager.GetString("ExceptionMsg_OwnerUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error - cannot reinitialize already initialized plugin..
        /// </summary>
        internal static string ExceptionMsg_PluginAlreadyInitialized {
            get {
                return ResourceManager.GetString("ExceptionMsg_PluginAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already initialized..
        /// </summary>
        internal static string ExceptionMsg_PluginManagerAlreadyInitialized {
            get {
                return ResourceManager.GetString("ExceptionMsg_PluginManagerAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete requested operation - this plugin has not been loaded yet..
        /// </summary>
        internal static string ExceptionMsg_PluginNotInitialized {
            get {
                return ResourceManager.GetString("ExceptionMsg_PluginNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error occurred, cannot return requested information. The singleton has not been initialized yet..
        /// </summary>
        internal static string ExceptionMsg_SingletonNotInitializedYet {
            get {
                return ResourceManager.GetString("ExceptionMsg_SingletonNotInitializedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while working with the Configuration Storage to load configuration..
        /// </summary>
        internal static string ExceptionMsg_UnableToLoadConfiguration_StorageError {
            get {
                return ResourceManager.GetString("ExceptionMsg_UnableToLoadConfiguration_StorageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while working with the Configuration Storage to save configuration..
        /// </summary>
        internal static string ExceptionMsg_UnableToSaveConfiguration_StorageError {
            get {
                return ResourceManager.GetString("ExceptionMsg_UnableToSaveConfiguration_StorageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unload plugin manager - cannot initiate shutdown from its own AppDomain..
        /// </summary>
        internal static string ExceptionMsg_UnableToUnloadPluginMangerFromCurrentAppDomain {
            get {
                return ResourceManager.GetString("ExceptionMsg_UnableToUnloadPluginMangerFromCurrentAppDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphen crashed.
        /// </summary>
        internal static string MsgBox_Caption_HyphenCrashed {
            get {
                return ResourceManager.GetString("MsgBox_Caption_HyphenCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Hyphen.
        /// </summary>
        internal static string MsgBox_Caption_HyphenLoadFailed {
            get {
                return ResourceManager.GetString("MsgBox_Caption_HyphenLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphen plugins.
        /// </summary>
        internal static string MsgBox_Caption_LoadUnloadPlugins {
            get {
                return ResourceManager.GetString("MsgBox_Caption_LoadUnloadPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load/unload plugins.
        /// </summary>
        internal static string MsgBox_Caption_LoadUnloadPluginsFailure {
            get {
                return ResourceManager.GetString("MsgBox_Caption_LoadUnloadPluginsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options available.
        /// </summary>
        internal static string MsgBox_Caption_NoOptionsAvailable {
            get {
                return ResourceManager.GetString("MsgBox_Caption_NoOptionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins enabled.
        /// </summary>
        internal static string MsgBox_Caption_NoPluginsLoaded {
            get {
                return ResourceManager.GetString("MsgBox_Caption_NoPluginsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins updated.
        /// </summary>
        internal static string MsgBox_Caption_PluginReloadComplete {
            get {
                return ResourceManager.GetString("MsgBox_Caption_PluginReloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime version problem.
        /// </summary>
        internal static string MsgBox_Caption_RuntimeVersionNotAvailable {
            get {
                return ResourceManager.GetString("MsgBox_Caption_RuntimeVersionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MsgBox_Caption_Warning {
            get {
                return ResourceManager.GetString("MsgBox_Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} error.
        /// </summary>
        internal static string MsgBox_Formatable1_Caption_PluginError {
            get {
                return ResourceManager.GetString("MsgBox_Formatable1_Caption_PluginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} updated.
        /// </summary>
        internal static string MsgBox_Formatable1_Caption_PluginUpdated {
            get {
                return ResourceManager.GetString("MsgBox_Formatable1_Caption_PluginUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Hyphen - {0}.
        /// </summary>
        internal static string MsgBox_Formatable1_Text_HyphenLoadFailed {
            get {
                return ResourceManager.GetString("MsgBox_Formatable1_Text_HyphenLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading/unloading managed plugins - {0}..
        /// </summary>
        internal static string MsgBox_Formatable1_Text_LoadUnloadPluginsFailure {
            get {
                return ResourceManager.GetString("MsgBox_Formatable1_Text_LoadUnloadPluginsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured in the {0} plugin, some information may be lost. However, the plugin will continue running..
        /// </summary>
        internal static string MsgBox_Formatable1_Text_ModuleError {
            get {
                return ResourceManager.GetString("MsgBox_Formatable1_Text_ModuleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the {1} plugin - {2}{0}{0}Press OK to disable the plugin, otherwise press Cancel..
        /// </summary>
        internal static string MsgBox_Formatable2_Text_PluginError {
            get {
                return ResourceManager.GetString("MsgBox_Formatable2_Text_PluginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some information may be lost. However, the plugin will continue running..
        /// </summary>
        internal static string MsgBox_Text_GenericPluginError {
            get {
                return ResourceManager.GetString("MsgBox_Text_GenericPluginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured in Hyphen. Please, contact its author to resolve the issue..
        /// </summary>
        internal static string MsgBox_Text_HyphenCrashed {
            get {
                return ResourceManager.GetString("MsgBox_Text_HyphenCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to disable all Hyphen plugins. Are you sure?.
        /// </summary>
        internal static string MsgBox_Text_LoadUnloadPlugins_Unload {
            get {
                return ResourceManager.GetString("MsgBox_Text_LoadUnloadPlugins_Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with Microsoft.net configuration files. These files are critical for Hyphen execution. The problem was corrected but Miranda must be restarted to apply changes..
        /// </summary>
        internal static string MsgBox_Text_MirandaRestartRequired {
            get {
                return ResourceManager.GetString("MsgBox_Text_MirandaRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin has no options to configure..
        /// </summary>
        internal static string MsgBox_Text_NoOptionsAvailable {
            get {
                return ResourceManager.GetString("MsgBox_Text_NoOptionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To perform the task, you have to enable the plugins first..
        /// </summary>
        internal static string MsgBox_Text_NoPluginsLoaded {
            get {
                return ResourceManager.GetString("MsgBox_Text_NoPluginsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphen plugins were successfully reloaded..
        /// </summary>
        internal static string MsgBox_Text_PluginReloadComplete {
            get {
                return ResourceManager.GetString("MsgBox_Text_PluginReloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphen plugins were updated. Do you wish to reload them?.
        /// </summary>
        internal static string MsgBox_Text_PluginUpdated {
            get {
                return ResourceManager.GetString("MsgBox_Text_PluginUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while preparing the report. Copy the details and visit http://forums.miranda-im.org for assistance..
        /// </summary>
        internal static string MsgBox_Text_UnableToReportError {
            get {
                return ResourceManager.GetString("MsgBox_Text_UnableToReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure .
        /// </summary>
        internal static string UI_Caption_Configure {
            get {
                return ResourceManager.GetString("UI_Caption_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string UI_Caption_Error {
            get {
                return ResourceManager.GetString("UI_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} crashed.
        /// </summary>
        internal static string UI_Formatable1_Text_PluginCrashed {
            get {
                return ResourceManager.GetString("UI_Formatable1_Text_PluginCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no items / plugins loaded).
        /// </summary>
        internal static string UI_Label_Empty {
            get {
                return ResourceManager.GetString("UI_Label_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (select a plugin).
        /// </summary>
        internal static string UI_Label_SelectPluginToDisplayDescr {
            get {
                return ResourceManager.GetString("UI_Label_SelectPluginToDisplayDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown&gt;.
        /// </summary>
        internal static string UI_Label_Unknown {
            get {
                return ResourceManager.GetString("UI_Label_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string UI_Text_ConfigureStandaloneModules {
            get {
                return ResourceManager.GetString("UI_Text_ConfigureStandaloneModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphen.
        /// </summary>
        internal static string UI_Text_Hyphen {
            get {
                return ResourceManager.GetString("UI_Text_Hyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable plugins.
        /// </summary>
        internal static string UI_Text_LoadUnloadPlugins {
            get {
                return ResourceManager.GetString("UI_Text_LoadUnloadPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage plugins....
        /// </summary>
        internal static string UI_Text_ManagePlugins {
            get {
                return ResourceManager.GetString("UI_Text_ManagePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string UI_Text_No {
            get {
                return ResourceManager.GetString("UI_Text_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra items....
        /// </summary>
        internal static string UI_Text_ShowManagedMainMenu {
            get {
                return ResourceManager.GetString("UI_Text_ShowManagedMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string UI_Text_Yes {
            get {
                return ResourceManager.GetString("UI_Text_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphen.
        /// </summary>
        internal static string UI_ToolTip_HyphenTrayIcon {
            get {
                return ResourceManager.GetString("UI_ToolTip_HyphenTrayIcon", resourceCulture);
            }
        }
    }
}
