// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Virtuoso.Miranda.Plugins.Infrastructure;
namespace Virtuoso.Miranda.Plugins.UnitTests
{
    /// <summary>
    ///This is a test class for Virtuoso.Miranda.Plugins.Infrastructure.ContactInfo and is intended
    ///to contain all Virtuoso.Miranda.Plugins.Infrastructure.ContactInfo Unit Tests
    ///</summary>
    [TestClass()]
    public class ContactInfoTest
    {
        private ContactInfo TestInstance;

        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion

        [TestInitialize]
        public void TestInitialize()
        {
            this.TestInstance = Virtuoso_Miranda_Plugins_Infrastructure_ContactInfoAccessor.CreatePrivate();
        }

        /// <summary>
        ///A test for CallContactService (string, UIntPtr, IntPtr)
        ///</summary>
        [TestMethod(), ExpectedException(typeof(ArgumentNullException))]
        public void CallContactServiceTest()
        {
            this.TestInstance.CallContactService(null, UIntPtr.Zero, IntPtr.Zero);
        }

        /// <summary>
        ///A test for SendMessage (string)
        ///</summary>
        [TestMethod(), ExpectedException(typeof(ArgumentNullException))]
        public void SendMessageTest()
        {
            this.TestInstance.SendMessage(null);
        }
    }
}
